
services:
  mariadb:
    build: ./services/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    build: ./services/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
  
    depends_on:
      - wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    volumes:
      - web_data:/var/www/html:ro

  wordpress:
    build: ./services/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=my_user
      - WORDPRESS_DB_PASSWORD=my_password
      - WORDPRESS_DB_NAME=my_database
    ports:
      - "9000:9000"
    volumes:
      - web_data:/var/www/html

volumes:
  mariadb_data:
  web_data:
