
services:
  mariadb:
    build: ./services/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    build: ./services/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
  
    # depends_on:
    #   - mariadb
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    volumes:
      - ./services/nginx/html:/var/www/html:ro

volumes:
  mariadb_data:
  # web_data:
